# Generated by Django 3.2.8 on 2021-10-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0008_alter_meetup_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
